-- Supabase Database Setup for Reservations

-- 1. Create the reservations table if it doesn't exist
CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  guests INTEGER NOT NULL,
  phone TEXT NOT NULL,
  notes TEXT,
  status TEXT DEFAULT 'Pending'::text
);

-- 2. Create the menu_items table if it doesn't exist
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  rating NUMERIC DEFAULT 5.0,
  image TEXT,
  category TEXT NOT NULL,
  status TEXT DEFAULT 'Available'::text,
  featured BOOLEAN DEFAULT true
);

-- 3. Create the orders table if it doesn't exist
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  customer TEXT NOT NULL,
  items TEXT NOT NULL,
  total TEXT NOT NULL,
  status TEXT DEFAULT 'Preparing'::text,
  payment_method TEXT NOT NULL
);

-- 4. Create the reviews table if it doesn't exist
CREATE TABLE IF NOT EXISTS reviews (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  customer TEXT NOT NULL,
  rating INTEGER NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  text TEXT NOT NULL,
  status TEXT DEFAULT 'Pending'::text
);

-- 5. Create the staff table if it doesn't exist
CREATE TABLE IF NOT EXISTS staff (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT DEFAULT 'Active'::text
);

-- 6. Create the customers table if it doesn't exist
CREATE TABLE IF NOT EXISTS customers (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT NOT NULL,
  orders INTEGER DEFAULT 0,
  spent TEXT NOT NULL
);

-- 7. Turn on Row Level Security (RLS) for all tables
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 8. Drop existing policies if they exist (to avoid duplication errors)
DROP POLICY IF EXISTS "Allow public inserts on reservations" ON reservations;
DROP POLICY IF EXISTS "Allow public select on reservations" ON reservations;
DROP POLICY IF EXISTS "Allow public update on reservations" ON reservations;

DROP POLICY IF EXISTS "Allow public inserts on menu_items" ON menu_items;
DROP POLICY IF EXISTS "Allow public select on menu_items" ON menu_items;
DROP POLICY IF EXISTS "Allow public update on menu_items" ON menu_items;
DROP POLICY IF EXISTS "Allow public delete on menu_items" ON menu_items;

DROP POLICY IF EXISTS "Allow public inserts on orders" ON orders;
DROP POLICY IF EXISTS "Allow public select on orders" ON orders;
DROP POLICY IF EXISTS "Allow public update on orders" ON orders;

DROP POLICY IF EXISTS "Allow public inserts on reviews" ON reviews;
DROP POLICY IF EXISTS "Allow public select on reviews" ON reviews;
DROP POLICY IF EXISTS "Allow public update on reviews" ON reviews;

DROP POLICY IF EXISTS "Allow public select on staff" ON staff;
DROP POLICY IF EXISTS "Allow public update on staff" ON staff;

DROP POLICY IF EXISTS "Allow public select on customers" ON customers;
DROP POLICY IF EXISTS "Allow public insert/update on customers" ON customers;

-- 9. Create public policies to allow public access (for development/testing)

-- Reservations Policies
CREATE POLICY "Allow public inserts on reservations" ON reservations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on reservations" ON reservations FOR SELECT USING (true);
CREATE POLICY "Allow public update on reservations" ON reservations FOR UPDATE USING (true);

-- Menu Items Policies
CREATE POLICY "Allow public inserts on menu_items" ON menu_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on menu_items" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Allow public update on menu_items" ON menu_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on menu_items" ON menu_items FOR DELETE USING (true);

-- Orders Policies
CREATE POLICY "Allow public inserts on orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public update on orders" ON orders FOR UPDATE USING (true);

-- Reviews Policies
CREATE POLICY "Allow public inserts on reviews" ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on reviews" ON reviews FOR SELECT USING (true);
CREATE POLICY "Allow public update on reviews" ON reviews FOR UPDATE USING (true);

-- Staff Policies
CREATE POLICY "Allow public select on staff" ON staff FOR SELECT USING (true);
CREATE POLICY "Allow public update on staff" ON staff FOR UPDATE USING (true);

-- Customers Policies
CREATE POLICY "Allow public select on customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on customers" ON customers FOR ALL USING (true);

